"""add product_code columns

Revision ID: 6d5fed57d463
Revises: 5dc027b4a146
Create Date: 2026-09-09 20:00:24.798616
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '6d5fed57d463'
down_revision = '5dc027b4a146'
branch_labels = None
depends_on = None

# create_type=False: тип создаётся явно ниже (см. комментарий в upgrade()), колонки только используют
# уже существующий тип и не должны пытаться пересоздать его при каждом add_column.
product_code_enum = sa.Enum('ARBITRPACK', 'JUSTICEPACK', name='productcode', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ИСПРАВЛЕНО (найдено не 5-агентным аудитом, а при последующей E2E-проверке этой сессии: миграция
    # была протестирована только на SQLite, где ENUM — это просто VARCHAR+CHECK и отдельного типа не
    # существует; при первом запуске на реальном, только что созданном Postgres она падала с ошибкой
    # `type "productcode" does not exist`). Причина: op.add_column(..., sa.Enum(...)) НЕ создаёт тип в
    # Postgres автоматически — CREATE TYPE эмитится SQLAlchemy только вокруг CREATE TABLE, а не вокруг
    # ALTER TABLE ADD COLUMN на уже существующей таблице. Тип нужно создавать явно.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        postgresql.ENUM('ARBITRPACK', 'JUSTICEPACK', name='productcode').create(bind, checkfirst=True)
    op.add_column('analytics_events', sa.Column('product_code', product_code_enum, server_default='ARBITRPACK', nullable=False))
    op.create_index(op.f('ix_analytics_events_product_code'), 'analytics_events', ['product_code'], unique=False)
    op.add_column('audit_events', sa.Column('product_code', product_code_enum, server_default='ARBITRPACK', nullable=False))
    op.create_index(op.f('ix_audit_events_product_code'), 'audit_events', ['product_code'], unique=False)
    op.add_column('payments', sa.Column('product_code', product_code_enum, server_default='ARBITRPACK', nullable=False))
    op.add_column('processing_jobs', sa.Column('product_code', product_code_enum, server_default='ARBITRPACK', nullable=False))
    op.add_column('upload_batches', sa.Column('product_code', product_code_enum, server_default='ARBITRPACK', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_batches', 'product_code')
    op.drop_column('processing_jobs', 'product_code')
    op.drop_column('payments', 'product_code')
    op.drop_index(op.f('ix_audit_events_product_code'), table_name='audit_events')
    op.drop_column('audit_events', 'product_code')
    op.drop_index(op.f('ix_analytics_events_product_code'), table_name='analytics_events')
    op.drop_column('analytics_events', 'product_code')
    # ### end Alembic commands ###
    # Найдено в launch-readiness аудите: autogenerate не добавляет DROP TYPE для Postgres ENUM —
    # без этого тип 'productcode' остаётся в каталоге после отката (не ломает следующий upgrade,
    # SQLAlchemy Enum.create() идемпотентен через checkfirst=True, но это не байт-в-байт откат
    # схемы). На SQLite отдельного типа ENUM не существует (хранится как VARCHAR+CHECK), поэтому
    # DROP TYPE применяется только на Postgres.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP TYPE IF EXISTS productcode")
